### ISSUE TITLE
Unable to generate sky mask，Can't seem to access huggingface_hub

### ISSUE THREAD

**Issue by zhouyue270** [zju3dv/street_gaussians#63]
An error occurred when generating the sky mask according to the instructions in the readme you gave, and it cannot be downloaded.
Can't seem to access huggingface_hub

(street-gaussian) detection@detection-Precision-7920-Tower:~/zhouyue/street_gaussians$ python script/waymo/generate_sky_mask.py --datadir script/waymo/waymo/processed/006 --sam_checkpoint sam_vit_h_4b8939.pth
Load Grounding DINO model
Traceback (most recent call last):
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/urllib3/connection.py", line 140, in _new_conn
    conn = connection.create_connection(
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script/waymo/generate_sky_mask.py", line 176, in <module>
    setup(args)
  File "script/waymo/generate_sky_mask.py", line 55, in setup
    groundingdino_model = load_model_hf(ckpt_repo_id, ckpt_filenmae, ckpt_config_filename)
  File "script/waymo/generate_sky_mask.py", line 36, in load_model_hf
    cache_config_file = hf_hub_download(repo_id=repo_id, filename=ckpt_config_filename)
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1339, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/detection/anaconda3/envs/street-gaussian/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1857, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(

huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by Jachaganhio** [comment]
try proxy if you're in China mainland

**Comment by yonglei123** [comment]
Maybe this is ok.
HF_ENDPOINT=https://hf-mirror.com python script/waymo/generate_sky_mask.py --datadir ./data/waymo/raw/796 --sam_checkpoint ./sam_vit_h_4b8939.pth

**Comment by zhouyue270** [comment]
> Maybe this is ok. HF_ENDPOINT=https://hf-mirror.com python script/waymo/generate_sky_mask.py --datadir ./data/waymo/raw/796 --sam_checkpoint ./sam_vit_h_4b8939.pth

Thanks for your help, do you know how to make KITTI data format？
