### ISSUE TITLE
No sampling points, the number of Gaussians is 0

### ISSUE THREAD

**Issue by zhouyue270** [zju3dv/street_gaussians#69]
Number of points to split: 18
Number of points to clone: 0
Number of points to split: 0
Traceback (most recent call last):
  File "train.py", line 409, in <module>
    training()
  File "train.py", line 287, in training
    scalars, tensors = gaussians.densify_and_prune(
  File "/home/detection/zhouyue/street_gaussians/lib/models/street_gaussian_model.py", line 588, in densify_and_prune
    scalars_, tensors_ = model.densify_and_prune(max_grad, min_opacity, prune_big_points)
  File "/home/detection/zhouyue/street_gaussians/lib/models/gaussian_model_actor.py", line 246, in densify_and_prune
    torch.all((samples_xyz >= self.min_xyz).view(num_gaussians, -1), dim=-1),
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
 36%|██████████████████████████████████████▏                                                                  | 18200/50000 [3:04:46<5:22:51,  
 Do you know what this problem is?

**Comment by DeppMeng** [comment]
Any update on this one? I also encountered this error
